USE [master]
GO

/****** Object:  Database [QLNHANVIEN]    Script Date: 9/6/2020 10:16:43 AM ******/
CREATE DATABASE [QLNHANVIEN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLNHANVIEN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLNHANVIEN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLNHANVIEN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLNHANVIEN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLNHANVIEN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLNHANVIEN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLNHANVIEN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLNHANVIEN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLNHANVIEN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLNHANVIEN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLNHANVIEN] SET  MULTI_USER 
GO

ALTER DATABASE [QLNHANVIEN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLNHANVIEN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLNHANVIEN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLNHANVIEN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLNHANVIEN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLNHANVIEN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLNHANVIEN] SET  READ_WRITE 
GO

